version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/loanapp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    depends_on:
      - mysqldb

    volumes:
      - ./Docker/loanapp.sql:/docker-entrypoint-initdb.d/loanapp.sql

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: loanapp
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
networks:
  springapimysql-net: